//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common.Notify.Stylers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotifyTemplateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifyTemplateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.Notify.Stylers.Resources.NotifyTemplateResource", typeof(NotifyTemplateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;&lt;td colspan=&quot;3&quot; style=&quot;height: 10px; line-height: 10px; background: #fff; padding: 0; margin: 0;&quot;&gt;&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///            &lt;td style=&quot;vertical-align: top; margin: 0; padding: 34px 0 0 0; width: 210px; height: 108px; background: #f6f6f6; -moz-border-radius-topleft: 6px; -webkit-border-top-left-radius: 6px; border-top-left-radius: 6px;&quot;&gt;
        ///              &lt;img src=&quot;%IMAGEPATH%/tech-100.png&quot; style=&quot;width:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FooterCommonV10 {
            get {
                return ResourceManager.GetString("FooterCommonV10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;&lt;td colspan=&quot;3&quot; style=&quot;height: 10px; line-height: 10px; background: #fff; padding: 0; margin: 0;&quot;&gt;&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///            &lt;td style=&quot;vertical-align: top; margin: 0; padding: 34px 0 0 0; width: 210px; height: 108px; background: #f6f6f6; -moz-border-radius-topleft: 6px; -webkit-border-top-left-radius: 6px; border-top-left-radius: 6px;&quot;&gt;
        ///              &lt;img src=&quot;%IMAGEPATH%/tech-100.png&quot; style=&quot;width:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FooterOpensourceV10 {
            get {
                return ResourceManager.GetString("FooterOpensourceV10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body background=&quot;#ffffff&quot; style=&quot;background: linear-gradient(#ffffff, #ffffff); background-color: #ffffff; font-family: Helvetica, Arial, Tahoma, sans-serif; margin: 0; padding: 0; text-align: center; width: 100%;&quot;&gt;   
        ///&lt;center style=&quot;table-layout:fixed; width:100%; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;&quot; &gt;
        ///        &lt;div style=&quot;margin-bottom:0; margin-left:auto; margin-right:auto; margin-top:0; max-width:600px;&quot; &gt;
        ///            &lt;table background=&quot;#ffffff&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlMaster {
            get {
                return ResourceManager.GetString("HtmlMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///&lt;td style=&quot;margin: 0; padding-top: 40px;&quot;&gt;
        ///&lt;table style=&quot;border-collapse: collapse; border: 0; border-spacing: 0; height: 24px; margin: auto; min-width: 180px; padding: 0; text-align: center; vertical-align: top; width: 31%;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///            &lt;td style=&quot;margin: 0; padding: 0; vertical-align: bottom;&quot;&gt;
        ///                &lt;a href=&quot;https://www.facebook.com/pages/Onl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SocialNetworksFooter {
            get {
                return ResourceManager.GetString("SocialNetworksFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;td class=&quot;fol&quot; style=&quot;color: #666666; font-family: &apos;Open Sans&apos;, Helvetica, Arial, Tahoma, sans-serif; font-size: 13px; line-height: 20px; margin: 0; padding: 40px 0 8px; vertical-align: top;&quot;&gt;
        ///        For any purchase questions, email us at &lt;a style=&quot;color: #FF6F3D; text-decoration: underline;&quot; target=&quot;_blank&quot; href=&quot;mailto:%SALESEMAIL%&quot;&gt;%SALESEMAIL%&lt;/a&gt;.
        ///    &lt;/td&gt;
        ///&lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;td class=&quot;fol&quot; style=&quot;color: #6666 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextForFooterUnsubsribe {
            get {
                return ResourceManager.GetString("TextForFooterUnsubsribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;td style=&quot;margin: 0; text-align: center; vertical-align: top; width: 600px;&quot;&gt;
        ///        &lt;a href=&quot;%SITEURL%&quot; style=&quot;color: #333333; display: block; font-size: 16px; font-weight: bold; line-height: 22px; margin-bottom: 32px; text-decoration: none;&quot; target=&quot;_blank&quot;&gt;
        ///            &lt;img src=&quot;%LOGO%&quot; style=&quot;border: 0 none; height: 360px; width: 600px; color: #333333; font-family: &apos;Open Sans&apos;, Helvetica, Arial, Tahoma, sans-serif; font-size: 40px; font-weight: 70 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TopGif {
            get {
                return ResourceManager.GetString("TopGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///          &lt;td colspan=&quot;3&quot; style=&quot;margin: 0; padding: 0; background-color: #f6f6f6; height: 65px; padding: 20px 0 0 30px;&quot;&gt;
        ///            &lt;div style=&quot;text-align: left; height: 65px; width: 570px; margin: 0; padding: 0;&quot;&gt;
        ///                &lt;a href=&quot;%SITEURL%&quot; style=&quot;text-decoration: none; display: inline-block; width: 386px; height: 44px; margin: 0; padding: 0;&quot; target=&quot;_blank&quot;&gt;
        ///                    &lt;img src=&quot;%LOGO%&quot; style=&quot;border: 0px none; width: 386px; height: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TopLogo {
            get {
                return ResourceManager.GetString("TopLogo", resourceCulture);
            }
        }
    }
}
