//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.AuditTrail {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuditReportResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditReportResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ASC.AuditTrail.AuditReportResource", typeof(AuditReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ActionCol {
            get {
                return ResourceManager.GetString("ActionCol", resourceCulture);
            }
        }
        
        public static string ActionIdCol {
            get {
                return ResourceManager.GetString("ActionIdCol", resourceCulture);
            }
        }
        
        public static string ActionTypeCol {
            get {
                return ResourceManager.GetString("ActionTypeCol", resourceCulture);
            }
        }
        
        public static string AdministratorAdded {
            get {
                return ResourceManager.GetString("AdministratorAdded", resourceCulture);
            }
        }
        
        public static string AdministratorDeleted {
            get {
                return ResourceManager.GetString("AdministratorDeleted", resourceCulture);
            }
        }
        
        public static string AdministratorMessageSettingsUpdated {
            get {
                return ResourceManager.GetString("AdministratorMessageSettingsUpdated", resourceCulture);
            }
        }
        
        public static string AdministratorOpenedFullAccess {
            get {
                return ResourceManager.GetString("AdministratorOpenedFullAccess", resourceCulture);
            }
        }
        
        public static string AttachActionType {
            get {
                return ResourceManager.GetString("AttachActionType", resourceCulture);
            }
        }
        
        public static string AuditSettingsUpdated {
            get {
                return ResourceManager.GetString("AuditSettingsUpdated", resourceCulture);
            }
        }
        
        public static string AuditTrailReportDownloaded {
            get {
                return ResourceManager.GetString("AuditTrailReportDownloaded", resourceCulture);
            }
        }
        
        public static string AuditTrailReportName {
            get {
                return ResourceManager.GetString("AuditTrailReportName", resourceCulture);
            }
        }
        
        public static string AuthorizationKeysSetting {
            get {
                return ResourceManager.GetString("AuthorizationKeysSetting", resourceCulture);
            }
        }
        
        public static string BrowserCol {
            get {
                return ResourceManager.GetString("BrowserCol", resourceCulture);
            }
        }
        
        public static string ColorThemeChanged {
            get {
                return ResourceManager.GetString("ColorThemeChanged", resourceCulture);
            }
        }
        
        public static string CookieSettingsUpdated {
            get {
                return ResourceManager.GetString("CookieSettingsUpdated", resourceCulture);
            }
        }
        
        public static string CopyActionType {
            get {
                return ResourceManager.GetString("CopyActionType", resourceCulture);
            }
        }
        
        public static string CreateActionType {
            get {
                return ResourceManager.GetString("CreateActionType", resourceCulture);
            }
        }
        
        public static string CustomNavigationSettingsUpdated {
            get {
                return ResourceManager.GetString("CustomNavigationSettingsUpdated", resourceCulture);
            }
        }
        
        public static string DateCol {
            get {
                return ResourceManager.GetString("DateCol", resourceCulture);
            }
        }
        
        public static string DefaultStartPageSettingsUpdated {
            get {
                return ResourceManager.GetString("DefaultStartPageSettingsUpdated", resourceCulture);
            }
        }
        
        public static string DeleteActionType {
            get {
                return ResourceManager.GetString("DeleteActionType", resourceCulture);
            }
        }
        
        public static string DetachActionType {
            get {
                return ResourceManager.GetString("DetachActionType", resourceCulture);
            }
        }
        
        public static string DnsSettingsUpdated {
            get {
                return ResourceManager.GetString("DnsSettingsUpdated", resourceCulture);
            }
        }
        
        public static string DocumentServiceLocationSetting {
            get {
                return ResourceManager.GetString("DocumentServiceLocationSetting", resourceCulture);
            }
        }
        
        public static string DocumentsForcesave {
            get {
                return ResourceManager.GetString("DocumentsForcesave", resourceCulture);
            }
        }
        
        public static string DocumentsOverwritingSettingsUpdated {
            get {
                return ResourceManager.GetString("DocumentsOverwritingSettingsUpdated", resourceCulture);
            }
        }
        
        public static string DocumentsProduct {
            get {
                return ResourceManager.GetString("DocumentsProduct", resourceCulture);
            }
        }
        
        public static string DocumentsSettingsModule {
            get {
                return ResourceManager.GetString("DocumentsSettingsModule", resourceCulture);
            }
        }
        
        public static string DocumentsStoreForcesave {
            get {
                return ResourceManager.GetString("DocumentsStoreForcesave", resourceCulture);
            }
        }
        
        public static string DocumentsThirdPartySettingsUpdated {
            get {
                return ResourceManager.GetString("DocumentsThirdPartySettingsUpdated", resourceCulture);
            }
        }
        
        public static string DocumentsUploadingFormatsSettingsUpdated {
            get {
                return ResourceManager.GetString("DocumentsUploadingFormatsSettingsUpdated", resourceCulture);
            }
        }
        
        public static string DownloadActionType {
            get {
                return ResourceManager.GetString("DownloadActionType", resourceCulture);
            }
        }
        
        public static string ExportActionType {
            get {
                return ResourceManager.GetString("ExportActionType", resourceCulture);
            }
        }
        
        public static string FileChangeOwner {
            get {
                return ResourceManager.GetString("FileChangeOwner", resourceCulture);
            }
        }
        
        public static string FileConverted {
            get {
                return ResourceManager.GetString("FileConverted", resourceCulture);
            }
        }
        
        public static string FileCopied {
            get {
                return ResourceManager.GetString("FileCopied", resourceCulture);
            }
        }
        
        public static string FileCopiedWithOverwriting {
            get {
                return ResourceManager.GetString("FileCopiedWithOverwriting", resourceCulture);
            }
        }
        
        public static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        public static string FileCreatedVersion {
            get {
                return ResourceManager.GetString("FileCreatedVersion", resourceCulture);
            }
        }
        
        public static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        public static string FileDeletedVersion {
            get {
                return ResourceManager.GetString("FileDeletedVersion", resourceCulture);
            }
        }
        
        public static string FileDownloaded {
            get {
                return ResourceManager.GetString("FileDownloaded", resourceCulture);
            }
        }
        
        public static string FileDownloadedAs {
            get {
                return ResourceManager.GetString("FileDownloadedAs", resourceCulture);
            }
        }
        
        public static string FileImported {
            get {
                return ResourceManager.GetString("FileImported", resourceCulture);
            }
        }
        
        public static string FileLocked {
            get {
                return ResourceManager.GetString("FileLocked", resourceCulture);
            }
        }
        
        public static string FileMoved {
            get {
                return ResourceManager.GetString("FileMoved", resourceCulture);
            }
        }
        
        public static string FileMovedToTrash {
            get {
                return ResourceManager.GetString("FileMovedToTrash", resourceCulture);
            }
        }
        
        public static string FileMovedWithOverwriting {
            get {
                return ResourceManager.GetString("FileMovedWithOverwriting", resourceCulture);
            }
        }
        
        public static string FileRenamed {
            get {
                return ResourceManager.GetString("FileRenamed", resourceCulture);
            }
        }
        
        public static string FileRestoreVersion {
            get {
                return ResourceManager.GetString("FileRestoreVersion", resourceCulture);
            }
        }
        
        public static string FilesDocumentSigned {
            get {
                return ResourceManager.GetString("FilesDocumentSigned", resourceCulture);
            }
        }
        
        public static string FileSendAccessLink {
            get {
                return ResourceManager.GetString("FileSendAccessLink", resourceCulture);
            }
        }
        
        public static string FilesModule {
            get {
                return ResourceManager.GetString("FilesModule", resourceCulture);
            }
        }
        
        public static string FilesRequestSign {
            get {
                return ResourceManager.GetString("FilesRequestSign", resourceCulture);
            }
        }
        
        public static string FileUnlocked {
            get {
                return ResourceManager.GetString("FileUnlocked", resourceCulture);
            }
        }
        
        public static string FileUpdated {
            get {
                return ResourceManager.GetString("FileUpdated", resourceCulture);
            }
        }
        
        public static string FileUpdatedAccess {
            get {
                return ResourceManager.GetString("FileUpdatedAccess", resourceCulture);
            }
        }
        
        public static string FileUpdatedRevisionComment {
            get {
                return ResourceManager.GetString("FileUpdatedRevisionComment", resourceCulture);
            }
        }
        
        public static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        public static string FolderCopied {
            get {
                return ResourceManager.GetString("FolderCopied", resourceCulture);
            }
        }
        
        public static string FolderCopiedWithOverwriting {
            get {
                return ResourceManager.GetString("FolderCopiedWithOverwriting", resourceCulture);
            }
        }
        
        public static string FolderCreated {
            get {
                return ResourceManager.GetString("FolderCreated", resourceCulture);
            }
        }
        
        public static string FolderDeleted {
            get {
                return ResourceManager.GetString("FolderDeleted", resourceCulture);
            }
        }
        
        public static string FolderMoved {
            get {
                return ResourceManager.GetString("FolderMoved", resourceCulture);
            }
        }
        
        public static string FolderMovedToTrash {
            get {
                return ResourceManager.GetString("FolderMovedToTrash", resourceCulture);
            }
        }
        
        public static string FolderMovedWithOverwriting {
            get {
                return ResourceManager.GetString("FolderMovedWithOverwriting", resourceCulture);
            }
        }
        
        public static string FolderRenamed {
            get {
                return ResourceManager.GetString("FolderRenamed", resourceCulture);
            }
        }
        
        public static string FoldersModule {
            get {
                return ResourceManager.GetString("FoldersModule", resourceCulture);
            }
        }
        
        public static string FolderUpdatedAccess {
            get {
                return ResourceManager.GetString("FolderUpdatedAccess", resourceCulture);
            }
        }
        
        public static string FollowActionType {
            get {
                return ResourceManager.GetString("FollowActionType", resourceCulture);
            }
        }
        
        public static string FullTextSearchSetting {
            get {
                return ResourceManager.GetString("FullTextSearchSetting", resourceCulture);
            }
        }
        
        public static string GeneralModule {
            get {
                return ResourceManager.GetString("GeneralModule", resourceCulture);
            }
        }
        
        public static string GreetingSettingsUpdated {
            get {
                return ResourceManager.GetString("GreetingSettingsUpdated", resourceCulture);
            }
        }
        
        public static string GroupCreated {
            get {
                return ResourceManager.GetString("GroupCreated", resourceCulture);
            }
        }
        
        public static string GroupDeleted {
            get {
                return ResourceManager.GetString("GroupDeleted", resourceCulture);
            }
        }
        
        public static string GroupsModule {
            get {
                return ResourceManager.GetString("GroupsModule", resourceCulture);
            }
        }
        
        public static string GroupUpdated {
            get {
                return ResourceManager.GetString("GroupUpdated", resourceCulture);
            }
        }
        
        public static string GuestAccount {
            get {
                return ResourceManager.GetString("GuestAccount", resourceCulture);
            }
        }
        
        public static string GuestActivated {
            get {
                return ResourceManager.GetString("GuestActivated", resourceCulture);
            }
        }
        
        public static string GuestCreated {
            get {
                return ResourceManager.GetString("GuestCreated", resourceCulture);
            }
        }
        
        public static string GuestCreatedViaInvite {
            get {
                return ResourceManager.GetString("GuestCreatedViaInvite", resourceCulture);
            }
        }
        
        public static string GuestImported {
            get {
                return ResourceManager.GetString("GuestImported", resourceCulture);
            }
        }
        
        public static string ImportActionType {
            get {
                return ResourceManager.GetString("ImportActionType", resourceCulture);
            }
        }
        
        public static string IpCol {
            get {
                return ResourceManager.GetString("IpCol", resourceCulture);
            }
        }
        
        public static string LanguageSettingsUpdated {
            get {
                return ResourceManager.GetString("LanguageSettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP authentication disabled.
        /// </summary>
        public static string LdapDisabled {
            get {
                return ResourceManager.GetString("LdapDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP authentication enabled.
        /// </summary>
        public static string LdapEnabled {
            get {
                return ResourceManager.GetString("LdapEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP synchronization completed.
        /// </summary>
        public static string LdapSync {
            get {
                return ResourceManager.GetString("LdapSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key uploaded.
        /// </summary>
        public static string LicenseKeyUploaded {
            get {
                return ResourceManager.GetString("LicenseKeyUploaded", resourceCulture);
            }
        }
        
        public static string LinkActionType {
            get {
                return ResourceManager.GetString("LinkActionType", resourceCulture);
            }
        }
        
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        public static string LoginFailBruteForce {
            get {
                return ResourceManager.GetString("LoginFailBruteForce", resourceCulture);
            }
        }
        
        public static string LoginFailDisabledProfile {
            get {
                return ResourceManager.GetString("LoginFailDisabledProfile", resourceCulture);
            }
        }
        
        public static string LoginFailInvalidCombination {
            get {
                return ResourceManager.GetString("LoginFailInvalidCombination", resourceCulture);
            }
        }
        
        public static string LoginFailIpSecurity {
            get {
                return ResourceManager.GetString("LoginFailIpSecurity", resourceCulture);
            }
        }
        
        public static string LoginFailRecaptcha {
            get {
                return ResourceManager.GetString("LoginFailRecaptcha", resourceCulture);
            }
        }
        
        public static string LoginFailSocialAccountNotFound {
            get {
                return ResourceManager.GetString("LoginFailSocialAccountNotFound", resourceCulture);
            }
        }
        
        public static string LoginFailViaApi {
            get {
                return ResourceManager.GetString("LoginFailViaApi", resourceCulture);
            }
        }
        
        public static string LoginFailViaApiSms {
            get {
                return ResourceManager.GetString("LoginFailViaApiSms", resourceCulture);
            }
        }
        
        public static string LoginFailViaApiSocialAccount {
            get {
                return ResourceManager.GetString("LoginFailViaApiSocialAccount", resourceCulture);
            }
        }
        
        public static string LoginFailViaApiTfa {
            get {
                return ResourceManager.GetString("LoginFailViaApiTfa", resourceCulture);
            }
        }
        
        public static string LoginFailViaSms {
            get {
                return ResourceManager.GetString("LoginFailViaSms", resourceCulture);
            }
        }
        
        public static string LoginFailViaSSO {
            get {
                return ResourceManager.GetString("LoginFailViaSSO", resourceCulture);
            }
        }
        
        public static string LoginFailViaTfaApp {
            get {
                return ResourceManager.GetString("LoginFailViaTfaApp", resourceCulture);
            }
        }
        
        public static string LoginHistoryReportDownloaded {
            get {
                return ResourceManager.GetString("LoginHistoryReportDownloaded", resourceCulture);
            }
        }
        
        public static string LoginHistoryReportName {
            get {
                return ResourceManager.GetString("LoginHistoryReportName", resourceCulture);
            }
        }
        
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaApiSocialAccount {
            get {
                return ResourceManager.GetString("LoginSuccessViaApiSocialAccount", resourceCulture);
            }
        }
        
        public static string LoginSuccessSocialApp {
            get {
                return ResourceManager.GetString("LoginSuccessSocialApp", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaApi {
            get {
                return ResourceManager.GetString("LoginSuccessViaApi", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaApiSms {
            get {
                return ResourceManager.GetString("LoginSuccessViaApiSms", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaApiTfa {
            get {
                return ResourceManager.GetString("LoginSuccessViaApiTfa", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaSms {
            get {
                return ResourceManager.GetString("LoginSuccessViaSms", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaSocialAccount {
            get {
                return ResourceManager.GetString("LoginSuccessViaSocialAccount", resourceCulture);
            }
        }
        
        public static string LoginSuccessViaSSO {
            get {
                return ResourceManager.GetString("LoginSuccessViaSSO", resourceCulture);
            }
        }
        
        public static string LoginSuccesViaTfaApp {
            get {
                return ResourceManager.GetString("LoginSuccesViaTfaApp", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string MailServiceSettingsUpdated {
            get {
                return ResourceManager.GetString("MailServiceSettingsUpdated", resourceCulture);
            }
        }
        
        public static string ModuleCol {
            get {
                return ResourceManager.GetString("ModuleCol", resourceCulture);
            }
        }
        
        public static string MoveActionType {
            get {
                return ResourceManager.GetString("MoveActionType", resourceCulture);
            }
        }
        
        public static string OthersProduct {
            get {
                return ResourceManager.GetString("OthersProduct", resourceCulture);
            }
        }
        
        public static string OwnerChanged {
            get {
                return ResourceManager.GetString("OwnerChanged", resourceCulture);
            }
        }
        
        public static string OwnerSentChangeOwnerInstructions {
            get {
                return ResourceManager.GetString("OwnerSentChangeOwnerInstructions", resourceCulture);
            }
        }
        
        public static string OwnerSentPortalDeactivationInstructions {
            get {
                return ResourceManager.GetString("OwnerSentPortalDeactivationInstructions", resourceCulture);
            }
        }
        
        public static string OwnerSentPortalDeleteInstructions {
            get {
                return ResourceManager.GetString("OwnerSentPortalDeleteInstructions", resourceCulture);
            }
        }
        
        public static string PageCol {
            get {
                return ResourceManager.GetString("PageCol", resourceCulture);
            }
        }
        
        public static string PasswordStrengthSettingsUpdated {
            get {
                return ResourceManager.GetString("PasswordStrengthSettingsUpdated", resourceCulture);
            }
        }
        
        public static string PeopleProduct {
            get {
                return ResourceManager.GetString("PeopleProduct", resourceCulture);
            }
        }
        
        public static string PlatformCol {
            get {
                return ResourceManager.GetString("PlatformCol", resourceCulture);
            }
        }
        
        public static string PortalAccessSettingsUpdated {
            get {
                return ResourceManager.GetString("PortalAccessSettingsUpdated", resourceCulture);
            }
        }
        
        public static string PortalDeactivated {
            get {
                return ResourceManager.GetString("PortalDeactivated", resourceCulture);
            }
        }
        
        public static string PortalDeleted {
            get {
                return ResourceManager.GetString("PortalDeleted", resourceCulture);
            }
        }
        
        public static string PrivacyRoomDisable {
            get {
                return ResourceManager.GetString("PrivacyRoomDisable", resourceCulture);
            }
        }
        
        public static string PrivacyRoomEnable {
            get {
                return ResourceManager.GetString("PrivacyRoomEnable", resourceCulture);
            }
        }
        
        public static string ProductAccessOpened {
            get {
                return ResourceManager.GetString("ProductAccessOpened", resourceCulture);
            }
        }
        
        public static string ProductAccessOpenedForGroups {
            get {
                return ResourceManager.GetString("ProductAccessOpenedForGroups", resourceCulture);
            }
        }
        
        public static string ProductAccessOpenedForUsers {
            get {
                return ResourceManager.GetString("ProductAccessOpenedForUsers", resourceCulture);
            }
        }
        
        public static string ProductAccessRestricted {
            get {
                return ResourceManager.GetString("ProductAccessRestricted", resourceCulture);
            }
        }
        
        public static string ProductAddedAdministrator {
            get {
                return ResourceManager.GetString("ProductAddedAdministrator", resourceCulture);
            }
        }
        
        public static string ProductCol {
            get {
                return ResourceManager.GetString("ProductCol", resourceCulture);
            }
        }
        
        public static string ProductDeletedAdministrator {
            get {
                return ResourceManager.GetString("ProductDeletedAdministrator", resourceCulture);
            }
        }
        
        public static string ProductsListUpdated {
            get {
                return ResourceManager.GetString("ProductsListUpdated", resourceCulture);
            }
        }
        
        public static string ProductsModule {
            get {
                return ResourceManager.GetString("ProductsModule", resourceCulture);
            }
        }
        
        public static string ReassignsActionType {
            get {
                return ResourceManager.GetString("ReassignsActionType", resourceCulture);
            }
        }
        
        public static string SendActionType {
            get {
                return ResourceManager.GetString("SendActionType", resourceCulture);
            }
        }
        
        public static string SentInviteInstructions {
            get {
                return ResourceManager.GetString("SentInviteInstructions", resourceCulture);
            }
        }
        
        public static string SessionCompleted {
            get {
                return ResourceManager.GetString("SessionCompleted", resourceCulture);
            }
        }
        
        public static string SessionStarted {
            get {
                return ResourceManager.GetString("SessionStarted", resourceCulture);
            }
        }
        
        public static string SettingsProduct {
            get {
                return ResourceManager.GetString("SettingsProduct", resourceCulture);
            }
        }
        
        public static string SSODisabled {
            get {
                return ResourceManager.GetString("SSODisabled", resourceCulture);
            }
        }
        
        public static string SSOEnabled {
            get {
                return ResourceManager.GetString("SSOEnabled", resourceCulture);
            }
        }
        
        public static string StartBackupSetting {
            get {
                return ResourceManager.GetString("StartBackupSetting", resourceCulture);
            }
        }
        
        public static string StartStorageDecryption {
            get {
                return ResourceManager.GetString("StartStorageDecryption", resourceCulture);
            }
        }
        
        public static string StartStorageEncryption {
            get {
                return ResourceManager.GetString("StartStorageEncryption", resourceCulture);
            }
        }
        
        public static string StartTransferSetting {
            get {
                return ResourceManager.GetString("StartTransferSetting", resourceCulture);
            }
        }
        
        public static string SystemAccount {
            get {
                return ResourceManager.GetString("SystemAccount", resourceCulture);
            }
        }
        
        public static string TargetIdCol {
            get {
                return ResourceManager.GetString("TargetIdCol", resourceCulture);
            }
        }
        
        public static string TeamTemplateChanged {
            get {
                return ResourceManager.GetString("TeamTemplateChanged", resourceCulture);
            }
        }
        
        public static string ThirdPartyCreated {
            get {
                return ResourceManager.GetString("ThirdPartyCreated", resourceCulture);
            }
        }
        
        public static string ThirdPartyDeleted {
            get {
                return ResourceManager.GetString("ThirdPartyDeleted", resourceCulture);
            }
        }
        
        public static string ThirdPartyUpdated {
            get {
                return ResourceManager.GetString("ThirdPartyUpdated", resourceCulture);
            }
        }
        
        public static string TimeTrackingModule {
            get {
                return ResourceManager.GetString("TimeTrackingModule", resourceCulture);
            }
        }
        
        public static string TimeZoneSettingsUpdated {
            get {
                return ResourceManager.GetString("TimeZoneSettingsUpdated", resourceCulture);
            }
        }
        
        public static string TrustedMailDomainSettingsUpdated {
            get {
                return ResourceManager.GetString("TrustedMailDomainSettingsUpdated", resourceCulture);
            }
        }
        
        public static string TwoFactorAuthenticationSettingsDisabled {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationSettingsDisabled", resourceCulture);
            }
        }
        
        public static string TwoFactorAuthenticationSettingsEnabledBySms {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationSettingsEnabledBySms", resourceCulture);
            }
        }
        
        public static string TwoFactorAuthenticationSettingsEnabledByTfaApp {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationSettingsEnabledByTfaApp", resourceCulture);
            }
        }
        
        public static string TwoFactorAuthenticationSettingsUpdated {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationSettingsUpdated", resourceCulture);
            }
        }
        
        public static string UnfollowActionType {
            get {
                return ResourceManager.GetString("UnfollowActionType", resourceCulture);
            }
        }
        
        public static string UnknownAccount {
            get {
                return ResourceManager.GetString("UnknownAccount", resourceCulture);
            }
        }
        
        public static string UnlinkActionType {
            get {
                return ResourceManager.GetString("UnlinkActionType", resourceCulture);
            }
        }
        
        public static string UpdateAccessActionType {
            get {
                return ResourceManager.GetString("UpdateAccessActionType", resourceCulture);
            }
        }
        
        public static string UpdateActionType {
            get {
                return ResourceManager.GetString("UpdateActionType", resourceCulture);
            }
        }
        
        public static string UploadActionType {
            get {
                return ResourceManager.GetString("UploadActionType", resourceCulture);
            }
        }
        
        public static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        public static string UserAddedAvatar {
            get {
                return ResourceManager.GetString("UserAddedAvatar", resourceCulture);
            }
        }
        
        public static string UserCol {
            get {
                return ResourceManager.GetString("UserCol", resourceCulture);
            }
        }
        
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        public static string UserCreatedViaInvite {
            get {
                return ResourceManager.GetString("UserCreatedViaInvite", resourceCulture);
            }
        }
        
        public static string UserDataReassigns {
            get {
                return ResourceManager.GetString("UserDataReassigns", resourceCulture);
            }
        }
        
        public static string UserDataRemoving {
            get {
                return ResourceManager.GetString("UserDataRemoving", resourceCulture);
            }
        }
        
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        public static string UserDeletedAvatar {
            get {
                return ResourceManager.GetString("UserDeletedAvatar", resourceCulture);
            }
        }
        
        public static string UserFileUpdated {
            get {
                return ResourceManager.GetString("UserFileUpdated", resourceCulture);
            }
        }
        
        public static string UserImported {
            get {
                return ResourceManager.GetString("UserImported", resourceCulture);
            }
        }
        
        public static string UserLinkedSocialAccount {
            get {
                return ResourceManager.GetString("UserLinkedSocialAccount", resourceCulture);
            }
        }
        
        public static string UsersDeleted {
            get {
                return ResourceManager.GetString("UsersDeleted", resourceCulture);
            }
        }
        
        public static string UserSentActivationInstructions {
            get {
                return ResourceManager.GetString("UserSentActivationInstructions", resourceCulture);
            }
        }
        
        public static string UserSentDeleteInstructions {
            get {
                return ResourceManager.GetString("UserSentDeleteInstructions", resourceCulture);
            }
        }
        
        public static string UserSentEmailInstructions {
            get {
                return ResourceManager.GetString("UserSentEmailInstructions", resourceCulture);
            }
        }
        
        public static string UserSentPasswordInstructions {
            get {
                return ResourceManager.GetString("UserSentPasswordInstructions", resourceCulture);
            }
        }
        
        public static string UsersModule {
            get {
                return ResourceManager.GetString("UsersModule", resourceCulture);
            }
        }
        
        public static string UsersSentActivationInstructions {
            get {
                return ResourceManager.GetString("UsersSentActivationInstructions", resourceCulture);
            }
        }
        
        public static string UsersUpdatedStatus {
            get {
                return ResourceManager.GetString("UsersUpdatedStatus", resourceCulture);
            }
        }
        
        public static string UsersUpdatedType {
            get {
                return ResourceManager.GetString("UsersUpdatedType", resourceCulture);
            }
        }
        
        public static string UserTfaDisconnected {
            get {
                return ResourceManager.GetString("UserTfaDisconnected", resourceCulture);
            }
        }
        
        public static string UserTfaGenerateCodes {
            get {
                return ResourceManager.GetString("UserTfaGenerateCodes", resourceCulture);
            }
        }
        
        public static string UserUnlinkedSocialAccount {
            get {
                return ResourceManager.GetString("UserUnlinkedSocialAccount", resourceCulture);
            }
        }
        
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        public static string UserUpdatedAvatarThumbnails {
            get {
                return ResourceManager.GetString("UserUpdatedAvatarThumbnails", resourceCulture);
            }
        }
        
        public static string UserUpdatedEmail {
            get {
                return ResourceManager.GetString("UserUpdatedEmail", resourceCulture);
            }
        }
        
        public static string UserUpdatedLanguage {
            get {
                return ResourceManager.GetString("UserUpdatedLanguage", resourceCulture);
            }
        }
        
        public static string UserUpdatedMobileNumber {
            get {
                return ResourceManager.GetString("UserUpdatedMobileNumber", resourceCulture);
            }
        }
        
        public static string UserUpdatedPassword {
            get {
                return ResourceManager.GetString("UserUpdatedPassword", resourceCulture);
            }
        }
        
        public static string RoomCreated {
            get {
                return ResourceManager.GetString("RoomCreated", resourceCulture);
            }
        }
        
        public static string RoomArchived {
            get {
                return ResourceManager.GetString("RoomArchived", resourceCulture);
            }
        }
        
        public static string RoomUnarchived {
            get {
                return ResourceManager.GetString("RoomUnarchived", resourceCulture);
            }
        }
        
        public static string RoomRenamed {
            get {
                return ResourceManager.GetString("RoomRenamed", resourceCulture);
            }
        }
        
        public static string RoomLogoCreated {
            get {
                return ResourceManager.GetString("RoomLogoCreated", resourceCulture);
            }
        }
        
        public static string RoomLogoDeleted {
            get {
                return ResourceManager.GetString("RoomLogoDeleted", resourceCulture);
            }
        }
        
        public static string RoomUpdateAccessForUser {
            get {
                return ResourceManager.GetString("RoomUpdateAccessForUser", resourceCulture);
            }
        }
        
        public static string RoomInvitationLinkUpdated {
            get {
                return ResourceManager.GetString("RoomInvitationLinkUpdated", resourceCulture);
            }
        }
        
        public static string RoomDeleted {
            get {
                return ResourceManager.GetString("RoomDeleted", resourceCulture);
            }
        }
        
        public static string AddedRoomTags {
            get {
                return ResourceManager.GetString("AddedRoomTags", resourceCulture);
            }
        }
        
        public static string DeletedRoomTags {
            get {
                return ResourceManager.GetString("DeletedRoomTags", resourceCulture);
            }
        }
        
        public static string TagCreated {
            get {
                return ResourceManager.GetString("TagCreated", resourceCulture);
            }
        }
        
        public static string TagsDeleted {
            get {
                return ResourceManager.GetString("TagsDeleted", resourceCulture);
            }
        }
        
        public static string RoomCreateUser {
            get {
                return ResourceManager.GetString("RoomCreateUser", resourceCulture);
            }
        }
        
        public static string RoomRemoveUser {
            get {
                return ResourceManager.GetString("RoomRemoveUser", resourceCulture);
            }
        }
        
        public static string RoomInvitationLinkCreated {
            get {
                return ResourceManager.GetString("RoomInvitationLinkCreated", resourceCulture);
            }
        }
        
        public static string RoomInvitationLinkDeleted {
            get {
                return ResourceManager.GetString("RoomInvitationLinkDeleted", resourceCulture);
            }
        }
        
        public static string RoomsModule {
            get {
                return ResourceManager.GetString("RoomsModule", resourceCulture);
            }
        }
        
        public static string TrashEmptied {
            get {
                return ResourceManager.GetString("TrashEmptied", resourceCulture);
            }
        }
        
        public static string CityCol {
            get {
                return ResourceManager.GetString("CityCol", resourceCulture);
            }
        }
        
        public static string CountryCol {
            get {
                return ResourceManager.GetString("CountryCol", resourceCulture);
            }
        }
        
        public static string RoomExternalLinkCreated {
            get {
                return ResourceManager.GetString("RoomExternalLinkCreated", resourceCulture);
            }
        }
        
        public static string RoomExternalLinkDeleted {
            get {
                return ResourceManager.GetString("RoomExternalLinkDeleted", resourceCulture);
            }
        }
        
        public static string RoomExternalLinkUpdated {
            get {
                return ResourceManager.GetString("RoomExternalLinkUpdated", resourceCulture);
            }
        }
        
        public static string FileOpenedForChange {
            get {
                return ResourceManager.GetString("FileOpenedForChange", resourceCulture);
            }
        }
        
        public static string PortalRenamed {
            get {
                return ResourceManager.GetString("PortalRenamed", resourceCulture);
            }
        }
        
        public static string SendJoinInvite {
            get {
                return ResourceManager.GetString("SendJoinInvite", resourceCulture);
            }
        }
        
        public static string RoomGroupAdded {
            get {
                return ResourceManager.GetString("RoomGroupAdded", resourceCulture);
            }
        }
        
        public static string RoomUpdateAccessForGroup {
            get {
                return ResourceManager.GetString("RoomUpdateAccessForGroup", resourceCulture);
            }
        }
        
        public static string RoomGroupRemove {
            get {
                return ResourceManager.GetString("RoomGroupRemove", resourceCulture);
            }
        }
        
        public static string FileUploadedWithOverwriting {
            get {
                return ResourceManager.GetString("FileUploadedWithOverwriting", resourceCulture);
            }
        }
        
        public static string QuotaPerRoomChanged {
            get {
                return ResourceManager.GetString("QuotaPerRoomChanged", resourceCulture);
            }
        }
        
        public static string QuotaPerRoomDisabled {
            get {
                return ResourceManager.GetString("QuotaPerRoomDisabled", resourceCulture);
            }
        }
        
        public static string QuotaPerUserChanged {
            get {
                return ResourceManager.GetString("QuotaPerUserChanged", resourceCulture);
            }
        }
        
        public static string QuotaPerUserDisabled {
            get {
                return ResourceManager.GetString("QuotaPerUserDisabled", resourceCulture);
            }
        }
        
        public static string QuotaPerPortalChanged {
            get {
                return ResourceManager.GetString("QuotaPerPortalChanged", resourceCulture);
            }
        }
        
        public static string QuotaPerPortalDisabled {
            get {
                return ResourceManager.GetString("QuotaPerPortalDisabled", resourceCulture);
            }
        }
        
        public static string FileSizePostfix {
            get {
                return ResourceManager.GetString("FileSizePostfix", resourceCulture);
            }
        }
        
        public static string RoomCopied {
            get {
                return ResourceManager.GetString("RoomCopied", resourceCulture);
            }
        }
        
        public static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        public static string FormOpenedForFilling {
            get {
                return ResourceManager.GetString("FormOpenedForFilling", resourceCulture);
            }
        }
        
        public static string CustomQuotaPerRoomChanged {
            get {
                return ResourceManager.GetString("CustomQuotaPerRoomChanged", resourceCulture);
            }
        }
        
        public static string CustomQuotaPerRoomDefault {
            get {
                return ResourceManager.GetString("CustomQuotaPerRoomDefault", resourceCulture);
            }
        }
        
        public static string CustomQuotaPerRoomDisabled {
            get {
                return ResourceManager.GetString("CustomQuotaPerRoomDisabled", resourceCulture);
            }
        }
        
        public static string CustomQuotaPerUserChanged {
            get {
                return ResourceManager.GetString("CustomQuotaPerUserChanged", resourceCulture);
            }
        }
        
        public static string CustomQuotaPerUserDefault {
            get {
                return ResourceManager.GetString("CustomQuotaPerUserDefault", resourceCulture);
            }
        }
        
        public static string CustomQuotaPerUserDisabled {
            get {
                return ResourceManager.GetString("CustomQuotaPerUserDisabled", resourceCulture);
            }
        }
        
        public static string RoomIndexingEnabled {
            get {
                return ResourceManager.GetString("RoomIndexingEnabled", resourceCulture);
            }
        }
        
        public static string RoomIndexingDisabled {
            get {
                return ResourceManager.GetString("RoomIndexingDisabled", resourceCulture);
            }
        }
        
        public static string RoomLifeTimeSet {
            get {
                return ResourceManager.GetString("RoomLifeTimeSet", resourceCulture);
            }
        }
        
        public static string RoomLifeTimeDisabled {
            get {
                return ResourceManager.GetString("RoomLifeTimeDisabled", resourceCulture);
            }
        }
        
        public static string FolderIndexChanged {
            get {
                return ResourceManager.GetString("FolderIndexChanged", resourceCulture);
            }
        }
        
        public static string FileIndexChanged {
            get {
                return ResourceManager.GetString("FileIndexChanged", resourceCulture);
            }
        }
        
        public static string FolderIndexReordered {
            get {
                return ResourceManager.GetString("FolderIndexReordered", resourceCulture);
            }
        }
        
        public static string RoomDenyDownloadEnabled {
            get {
                return ResourceManager.GetString("RoomDenyDownloadEnabled", resourceCulture);
            }
        }
        
        public static string RoomDenyDownloadDisabled {
            get {
                return ResourceManager.GetString("RoomDenyDownloadDisabled", resourceCulture);
            }
        }
        
        public static string RoomWatermarkSet {
            get {
                return ResourceManager.GetString("RoomWatermarkSet", resourceCulture);
            }
        }
        
        public static string RoomWatermarkDisabled {
            get {
                return ResourceManager.GetString("RoomWatermarkDisabled", resourceCulture);
            }
        }
        
        public static string RoomIndexExportSaved {
            get {
                return ResourceManager.GetString("RoomIndexExportSaved", resourceCulture);
            }
        }
        
        public static string RoomInviteResend {
            get {
                return ResourceManager.GetString("RoomInviteResend", resourceCulture);
            }
        }
        
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        public static string UpdateClient {
            get {
                return ResourceManager.GetString("UpdateClient", resourceCulture);
            }
        }
        
        public static string RegenerateSecret {
            get {
                return ResourceManager.GetString("RegenerateSecret", resourceCulture);
            }
        }
        
        public static string DeleteClient {
            get {
                return ResourceManager.GetString("DeleteClient", resourceCulture);
            }
        }
        
        public static string ChangeClientActivation {
            get {
                return ResourceManager.GetString("ChangeClientActivation", resourceCulture);
            }
        }
        
        public static string ChangeClientVisibility {
            get {
                return ResourceManager.GetString("ChangeClientVisibility", resourceCulture);
            }
        }
        
        public static string RevokeUserClient {
            get {
                return ResourceManager.GetString("RevokeUserClient", resourceCulture);
            }
        }
        
        public static string GenerateAuthorizationCodeToken {
            get {
                return ResourceManager.GetString("GenerateAuthorizationCodeToken", resourceCulture);
            }
        }
        
        public static string GeneratePersonalAccessToken {
            get {
                return ResourceManager.GetString("GeneratePersonalAccessToken", resourceCulture);
            }
        }
        
        public static string OAuthModule {
            get {
                return ResourceManager.GetString("OAuthModule", resourceCulture);
            }
        }
        
        public static string FileVersionRemoved {
            get {
                return ResourceManager.GetString("FileVersionRemoved", resourceCulture);
            }
        }
        
        public static string DevToolsAccessSettingsChanged {
            get {
                return ResourceManager.GetString("DevToolsAccessSettingsChanged", resourceCulture);
            }
        }
        
        public static string WebhookCreated {
            get {
                return ResourceManager.GetString("WebhookCreated", resourceCulture);
            }
        }
        
        public static string WebhookDeleted {
            get {
                return ResourceManager.GetString("WebhookDeleted", resourceCulture);
            }
        }
        
        public static string WebhookUpdated {
            get {
                return ResourceManager.GetString("WebhookUpdated", resourceCulture);
            }
        }
        
        public static string FormStartedToFill {
            get {
                return ResourceManager.GetString("FormStartedToFill", resourceCulture);
            }
        }
        
        public static string FormPartiallyFilled {
            get {
                return ResourceManager.GetString("FormPartiallyFilled", resourceCulture);
            }
        }
        
        public static string FormCompletelyFilled {
            get {
                return ResourceManager.GetString("FormCompletelyFilled", resourceCulture);
            }
        }
        
        public static string FormStopped {
            get {
                return ResourceManager.GetString("FormStopped", resourceCulture);
            }
        }
        
        public static string FileCustomFilterDisabled {
            get {
                return ResourceManager.GetString("FileCustomFilterDisabled", resourceCulture);
            }
        }
        
        public static string FileCustomFilterEnabled {
            get {
                return ResourceManager.GetString("FileCustomFilterEnabled", resourceCulture);
            }
        }
        
        public static string ApiKeyCreated {
            get {
                return ResourceManager.GetString("ApiKeyCreated", resourceCulture);
            }
        }
        
        public static string ApiKeyUpdated {
            get {
                return ResourceManager.GetString("ApiKeyUpdated", resourceCulture);
            }
        }
        
        public static string ApiKeyDeleted {
            get {
                return ResourceManager.GetString("ApiKeyDeleted", resourceCulture);
            }
        }
    }
}
