// Copyright (C) Ascensio System SIA, 2009-2026
// 
// This program is a free software product. You can redistribute it and/or
// modify it under the terms of the GNU Affero General Public License (AGPL)
// version 3 as published by the Free Software Foundation, together with the
// additional terms provided in the LICENSE file.
// 
// This program is distributed WITHOUT ANY WARRANTY, without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
// details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
// 
// You can contact Ascensio System SIA by email at info@onlyoffice.com
// or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
// LV-1050, Latvia, European Union.
// 
// The interactive user interfaces in modified versions of the Program
// are required to display Appropriate Legal Notices in accordance with
// Section 5 of the GNU AGPL version 3.
// 
// No trademark rights are granted under this License.
// 
// All non-code elements of the Product, including illustrations,
// icon sets, and technical writing content, are licensed under the
// Creative Commons Attribution-ShareAlike 4.0 International License:
// https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// This license applies only to such non-code elements and does not
// modify or replace the licensing terms applicable to the Program's
// source code, which remains licensed under the GNU Affero General
// Public License v3.
// 
// SPDX-License-Identifier: AGPL-3.0-only

namespace ASC.People.ApiModels.RequestDto;

/// <summary>
/// The request parameters for getting accounts.
/// </summary>
public class AccountsEntriesRequestDto<T>
{
    /// <summary>
    /// The ID of the room, folder or file whose access the search is run against, taken from the route. It is an
    /// integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected
    /// third-party storage.
    /// </summary>
    /// <example>1234</example>
    [FromRoute(Name = "id")]
    public required T Id { get; set; }

    /// <summary>
    /// Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled
    /// one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state.
    /// </summary>
    /// <example>Active</example>
    [FromQuery(Name = "employeeStatus")]
    public EmployeeStatus? EmployeeStatus { get; set; }

    /// <summary>
    /// Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never
    /// been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is
    /// still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state.
    /// </summary>
    /// <example>Activated</example>
    [FromQuery(Name = "activationStatus")]
    public EmployeeActivationStatus? ActivationStatus { get; set; }

    /// <summary>
    /// Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new
    /// members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "excludeShared")]
    public bool? ExcludeShared { get; set; }

    /// <summary>
    /// Keeps only the accounts that already have access to the entry, which is the set to offer when changing or
    /// revoking access. Every returned entry has `shared` set to true, and the flag is ignored when
    /// `excludeShared` is also set.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "includeShared")]
    public bool? IncludeShared { get; set; }

    /// <summary>
    /// Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.
    /// Omit it to search regardless of who sent the invitation.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "invitedByMe")]
    public bool? InvitedByMe { get; set; }

    /// <summary>
    /// Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the
    /// invitation.
    /// </summary>
    /// <example>00000000-0000-0000-0000-000000000000</example>
    [FromQuery(Name = "inviterId")]
    public Guid? InviterId { get; set; }

    /// <summary>
    /// The part of the portal to search in: `All`, the default, searches members and guests together, `People`
    /// leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace
    /// administrator, only the guests that caller is related to.
    /// </summary>
    /// <example>All</example>
    [FromQuery(Name = "area")]
    public Area Area { get; set; } = Area.All;

    /// <summary>
    /// Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,
    /// searches every type.
    /// </summary>
    /// <example>["RoomAdmin", "Guest"]</example>
    [FromQuery(Name = "employeeTypes")]
    public IEnumerable<EmployeeType> EmployeeTypes { get; set; } = new List<EmployeeType>();

    /// <summary>
    /// The size of the page, counting groups and users together. It defaults to 100, which is also the largest value
    /// the operation accepts.
    /// </summary>
    /// <example>25</example>
    [FromQuery(Name = "count")]
    [Range(1, ApiContext.MaxCount)]
    public int Count { get; set; } = ApiContext.DefaultCount;

    /// <summary>
    /// The number of matches to skip before the page starts, counted over the groups and users together. It defaults
    /// to 0, and the total number of matches is reported in the total count of the response.
    /// </summary>
    /// <example>0</example>
    [FromQuery(Name = "startIndex")]
    public int StartIndex { get; set; }

    /// <summary>
    /// The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the
    /// value on spaces instead, in which case every term has to match.
    /// </summary>
    /// <example>,</example>
    [FromQuery(Name = "filterSeparator")]
    public string FilterSeparator { get; set; }

    /// <summary>
    /// The text to search for, matched case-insensitively against the first name, the last name and the email. It is
    /// required in practice: while it is empty the search returns nothing at all rather than every account.
    /// </summary>
    /// <example>John</example>
    [FromQuery(Name = "filterValue")]
    public string Text { get; set; }
}