// Copyright (C) Ascensio System SIA, 2009-2026
// 
// This program is a free software product. You can redistribute it and/or
// modify it under the terms of the GNU Affero General Public License (AGPL)
// version 3 as published by the Free Software Foundation, together with the
// additional terms provided in the LICENSE file.
// 
// This program is distributed WITHOUT ANY WARRANTY, without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
// details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
// 
// You can contact Ascensio System SIA by email at info@onlyoffice.com
// or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
// LV-1050, Latvia, European Union.
// 
// The interactive user interfaces in modified versions of the Program
// are required to display Appropriate Legal Notices in accordance with
// Section 5 of the GNU AGPL version 3.
// 
// No trademark rights are granted under this License.
// 
// All non-code elements of the Product, including illustrations,
// icon sets, and technical writing content, are licensed under the
// Creative Commons Attribution-ShareAlike 4.0 International License:
// https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// This license applies only to such non-code elements and does not
// modify or replace the licensing terms applicable to the Program's
// source code, which remains licensed under the GNU Affero General
// Public License v3.
// 
// SPDX-License-Identifier: AGPL-3.0-only

namespace ASC.People.ApiModels.RequestDto;

/// <summary>
/// The filter request parameters.
/// </summary>
public class SimpleByFilterRequestDto
{
    /// <summary>
    /// Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones
    /// and `Pending` for open invitations. Omit it to search every state.
    /// </summary>
    /// <example>Active</example>
    [FromQuery(Name = "employeeStatus")]
    public EmployeeStatus? EmployeeStatus { get; set; }

    /// <summary>
    /// Keeps only the members of this group, or excludes them when `excludeGroup` is true. It is ignored when
    /// `withoutGroup` is set.
    /// </summary>
    /// <example>00000000-0000-0000-0000-000000000000</example>
    [FromQuery(Name = "groupId")]
    public Guid? GroupId { get; set; }

    /// <summary>
    /// Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or
    /// `AutoGenerated`. Omit it to search every state.
    /// </summary>
    /// <example>Activated</example>
    [FromQuery(Name = "activationStatus")]
    public EmployeeActivationStatus? ActivationStatus { get; set; }

    /// <summary>
    /// Keeps only the accounts of this single type: `DocSpaceAdmin`, `RoomAdmin`, `User` or `Guest`. When it is
    /// sent it wins over `employeeTypes`, and a type that contradicts `area` is dropped.
    /// </summary>
    /// <example>RoomAdmin</example>
    [FromQuery(Name = "employeeType")]
    public EmployeeType? EmployeeType { get; set; }

    /// <summary>
    /// Keeps the accounts of any of the listed types, combined as alternatives. It is ignored when `employeeType`
    /// is also sent.
    /// </summary>
    /// <example>["RoomAdmin", "Guest"]</example>
    [FromQuery(Name = "employeeTypes")]
    public EmployeeType[] EmployeeTypes { get; set; }

    /// <summary>
    /// Set it to true to keep only the DocSpace administrators and the module administrators. Setting it to false
    /// is the same as omitting it and does not exclude administrators.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "isAdministrator")]
    public bool? IsAdministrator { get; set; }

    /// <summary>
    /// Keeps only the accounts that take a paid seat when `Paid`, or only the guests and members that do not when
    /// `Free`. Omit it to search both.
    /// </summary>
    /// <example>Paid</example>
    [FromQuery(Name = "payments")]
    public Payments? Payments { get; set; }

    /// <summary>
    /// Keeps only the accounts that sign in this way: `SSO`, `LDAP`, or `Standart` for an ordinary portal
    /// password. Omit it to search all of them.
    /// </summary>
    /// <example>Standart</example>
    [FromQuery(Name = "accountLoginType")]
    public AccountLoginType? AccountLoginType { get; set; }

    /// <summary>
    /// Keeps only the accounts whose storage quota is the portal default when `Default`, or set individually when
    /// `Custom`. `All`, which is the same as omitting the field, searches both.
    /// </summary>
    /// <example>Custom</example>
    [FromQuery(Name = "quotaFilter")]
    public QuotaFilter? QuotaFilter { get; set; }

    /// <summary>
    /// Set it to true to keep only the accounts that belong to no group at all, which makes `groupId` and
    /// `excludeGroup` irrelevant.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "withoutGroup")]
    public bool? WithoutGroup { get; set; }

    /// <summary>
    /// Inverts `groupId`: with true the members of that group are left out instead of being the only ones kept. It
    /// has no effect without `groupId`.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "excludeGroup")]
    public bool? ExcludeGroup { get; set; }

    /// <summary>
    /// Keeps only the accounts invited by the caller when true, and only those invited by somebody else when
    /// false. Omit it to search regardless of who sent the invitation.
    /// </summary>
    /// <example>false</example>
    [FromQuery(Name = "invitedByMe")]
    public bool? InvitedByMe { get; set; }

    /// <summary>
    /// Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the
    /// invitation.
    /// </summary>
    /// <example>00000000-0000-0000-0000-000000000000</example>
    [FromQuery(Name = "inviterId")]
    public Guid? InviterId { get; set; }

    /// <summary>
    /// The part of the portal to search in: `All`, the default, searches members and guests together, `People`
    /// leaves the guests out, and `Guests` returns guests only. It also cancels the type filters that contradict
    /// it.
    /// </summary>
    /// <example>All</example>
    [FromQuery(Name = "area")]
    public Area Area { get; set; } = Area.All;

    /// <summary>
    /// The size of the page. It defaults to 100, which is also the largest value the operation accepts.
    /// </summary>
    /// <example>25</example>
    [FromQuery(Name = "count")]
    [Range(1, ApiContext.MaxCount)]
    public int Count { get; set; } = ApiContext.DefaultCount;

    /// <summary>
    /// The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is
    /// reported in the total count of the response.
    /// </summary>
    /// <example>0</example>
    [FromQuery(Name = "startIndex")]
    public int StartIndex { get; set; }

    /// <summary>
    /// What to order the accounts by, compared without regard to case: `FirstName`, `LastName`, `DisplayName`,
    /// `Type`, `Email`, `Department`, `UsedSpace`, `CreatedBy` or `RegistrationDate`.
    /// </summary>
    /// <example>DisplayName</example>
    [FromQuery(Name = "sortBy")]
    public string SortBy { get; set; }

    /// <summary>
    /// The direction of the ordering: `Ascending`, which is the default, or `Descending`.
    /// </summary>
    /// <example>Ascending</example>
    [FromQuery(Name = "sortOrder")]
    public SortOrder SortOrder { get; set; }

    /// <summary>
    /// The character that splits `filterValue` into several terms, of which any one may match. Omit it to split
    /// the value on spaces instead, in which case every term has to match.
    /// </summary>
    /// <example>,</example>
    [FromQuery(Name = "filterSeparator")]
    public string FilterSeparator { get; set; }

    /// <summary>
    /// The text to match against the first name, the last name and the email, case-insensitively. Omit it to apply
    /// no text filter at all.
    /// </summary>
    /// <example>John</example>
    [FromQuery(Name = "filterValue")]
    public string Text { get; set; }
}