// Copyright (C) Ascensio System SIA, 2009-2026
// 
// This program is a free software product. You can redistribute it and/or
// modify it under the terms of the GNU Affero General Public License (AGPL)
// version 3 as published by the Free Software Foundation, together with the
// additional terms provided in the LICENSE file.
// 
// This program is distributed WITHOUT ANY WARRANTY, without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
// details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
// 
// You can contact Ascensio System SIA by email at info@onlyoffice.com
// or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
// LV-1050, Latvia, European Union.
// 
// The interactive user interfaces in modified versions of the Program
// are required to display Appropriate Legal Notices in accordance with
// Section 5 of the GNU AGPL version 3.
// 
// No trademark rights are granted under this License.
// 
// All non-code elements of the Product, including illustrations,
// icon sets, and technical writing content, are licensed under the
// Creative Commons Attribution-ShareAlike 4.0 International License:
// https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// This license applies only to such non-code elements and does not
// modify or replace the licensing terms applicable to the Program's
// source code, which remains licensed under the GNU Affero General
// Public License v3.
// 
// SPDX-License-Identifier: AGPL-3.0-only

namespace ASC.People.ApiModels.RequestDto;

/// <summary>
/// The request parameters for updating the user information.
/// </summary>
public class UpdateMembersRequestDto
{
    /// <summary>
    /// The accounts the operation applies to. System accounts are dropped from the list without an error, and the
    /// remaining ones are processed in the order they are given.
    /// </summary>
    /// <example>["00000000-0000-0000-0000-000000000000", "11111111-1111-1111-1111-111111111111"]</example>
    public IEnumerable<Guid> UserIds { get; set; }

    /// <summary>
    /// Reaches every pending account of the portal instead of the ones in `userIds`. It is read only by
    /// `PUT api/2.0/people/invite` and is ignored by every other operation that binds this body.
    /// </summary>
    /// <example>false</example>
    public bool ResendAll { get; set; }
}

/// <summary>
/// The request parameters for updating the user status.
/// </summary>
public class UpdateMemberStatusRequestDto
{
    /// <summary>
    /// The state to put the listed accounts into, taken from the route. Only `Active`, which enables an account,
    /// and `Terminated`, which disables it, are accepted; any other value is rejected with 400.
    /// </summary>
    /// <example>Active</example>
    [FromRoute(Name = "status")]
    public required EmployeeStatus Status { get; set; }

    /// <summary>
    /// The accounts to enable or disable. Only `userIds` is read by this operation; `resendAll` belongs to the
    /// invitation operations and is ignored here.
    /// </summary>
    /// <example>{"userIds":["00000000-0000-0000-0000-000000000000"]}</example>
    [FromBody]
    public required UpdateMembersRequestDto UpdateMembers { get; set; }
}

/// <summary>
/// The request parameters for updating the user type.
/// </summary>
public class UpdateMemberTypeRequestDto
{
    /// <summary>
    /// The type to convert the listed accounts to, taken from the route: `User`, `Guest`, `RoomAdmin` or
    /// `DocSpaceAdmin`. `RoomAdmin` and `DocSpaceAdmin` take a paid seat.
    /// </summary>
    /// <example>RoomAdmin</example>
    [FromRoute(Name = "type")]
    public required EmployeeType Type { get; set; }

    /// <summary>
    /// The accounts to convert. Only `userIds` is read by this operation; `resendAll` belongs to the invitation
    /// operations and is ignored here.
    /// </summary>
    /// <example>{"userIds":["00000000-0000-0000-0000-000000000000"]}</example>
    [FromBody]
    public required UpdateMembersRequestDto UpdateMembers { get; set; }
}

/// <summary>
/// The request parameters for updating the user activation status.
/// </summary>
public class UpdateMemberActivationStatusRequestDto
{
    /// <summary>
    /// The activation state to set on the calling account, taken from the route: `NotActivated`, `Activated`,
    /// `Pending` or `AutoGenerated`.
    /// </summary>
    /// <example>Activated</example>
    [FromRoute(Name = "activationstatus")]
    public required EmployeeActivationStatus ActivationStatus { get; set; }

    /// <summary>
    /// The account to change. Only `userIds` is read, it has to hold exactly one entry, and that entry has to be the
    /// calling account; `resendAll` is ignored here.
    /// </summary>
    /// <example>{"userIds":["00000000-0000-0000-0000-000000000000"]}</example>
    [FromBody]
    public required UpdateMembersRequestDto UpdateMembers { get; set; }
}