// Copyright (C) Ascensio System SIA, 2009-2026
//
// This program is a free software product. You can redistribute it and/or
// modify it under the terms of the GNU Affero General Public License (AGPL)
// version 3 as published by the Free Software Foundation, together with the
// additional terms provided in the LICENSE file.
//
// This program is distributed WITHOUT ANY WARRANTY, without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
// details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
//
// You can contact Ascensio System SIA by email at info@onlyoffice.com
// or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
// LV-1050, Latvia, European Union.
//
// The interactive user interfaces in modified versions of the Program
// are required to display Appropriate Legal Notices in accordance with
// Section 5 of the GNU AGPL version 3.
//
// No trademark rights are granted under this License.
//
// All non-code elements of the Product, including illustrations,
// icon sets, and technical writing content, are licensed under the
// Creative Commons Attribution-ShareAlike 4.0 International License:
// https://creativecommons.org/licenses/by-sa/4.0/legalcode
//
// This license applies only to such non-code elements and does not
// modify or replace the licensing terms applicable to the Program's
// source code, which remains licensed under the GNU Affero General
// Public License v3.
//
// SPDX-License-Identifier: AGPL-3.0-only

namespace ASC.Api.Core.Webhook.Payloads;

/// <summary>
/// Builds the payload of a user.* webhook.
/// </summary>
/// <remarks>
/// Deliberately not EmployeeFullDtoHelper. That helper answers "what may the current user see about this
/// user" - it gates groups, quota, CreatedBy and TfaAppEnabled on the caller's role, and a webhook has no
/// caller in that sense. This one answers "what is this user", the same way for every subscription, and
/// leaves the question of who may receive it to WebhookUserAccessChecker.
/// </remarks>
[Scope]
public class UserWebhookDtoHelper(
    UserManager userManager,
    UserPhotoManager userPhotoManager,
    DisplayUserSettingsHelper displayUserSettingsHelper,
    CommonLinkUtility commonLinkUtility,
    WebItemSecurity webItemSecurity,
    WebItemManager webItemManager,
    SettingsManager settingsManager,
    IQuotaService quotaService,
    TenantManager tenantManager,
    CoreBaseSettings coreBaseSettings)
{
    public async Task<UserWebhookDto> GetAsync(UserInfo userInfo)
    {
        var tenant = tenantManager.GetCurrentTenant();
        var currentType = await userManager.GetUserTypeAsync(userInfo.Id);

        var result = new UserWebhookDto
        {
            Id = userInfo.Id,
            DisplayName = displayUserSettingsHelper.GetFullUserName(userInfo),
            FirstName = userInfo.FirstName,
            LastName = userInfo.LastName,
            UserName = userInfo.UserName,
            Email = userInfo.Email,
            Status = userInfo.Status,
            ActivationStatus = userInfo.ActivationStatus & ~EmployeeActivationStatus.AutoGenerated,
            Terminated = userInfo.TerminatedDate,
            Location = userInfo.Location,
            Notes = userInfo.Notes,
            IsOwner = userInfo.IsOwner(tenant),
            IsAdmin = currentType is EmployeeType.DocSpaceAdmin && !userInfo.IsOwner(tenant),
            IsRoomAdmin = currentType is EmployeeType.RoomAdmin,
            IsCollaborator = currentType is EmployeeType.User,
            IsVisitor = await userManager.IsGuestAsync(userInfo),
            IsLDAP = userInfo.IsLDAP(),
            IsSSO = userInfo.IsSSO(),
            MobilePhone = userInfo.MobilePhone,
            MobilePhoneActivationStatus = userInfo.MobilePhoneActivationStatus,
            RegistrationDate = userInfo.CreateDate
        };

        if (!string.IsNullOrEmpty(userInfo.CultureName))
        {
            result.CultureName = coreBaseSettings.GetRightCultureName(userInfo.GetCulture());
        }

        FillContacts(result, userInfo);
        await FillGroupsAsync(result, userInfo);
        await FillAvatarsAsync(result, userInfo);
        await FillQuotaAsync(result, userInfo, tenant);

        var listAdminModules = await userInfo.GetListAdminModulesAsync(webItemSecurity, webItemManager);
        if (listAdminModules.Count > 0)
        {
            result.ListAdminModules = listAdminModules;
        }

        if (userInfo.CreatedBy.HasValue)
        {
            result.CreatedBy = await GetSummaryAsync(userInfo.CreatedBy.Value);
        }

        return result;
    }

    public async Task<UserSummaryWebhookDto> GetSummaryAsync(Guid userId)
    {
        var userInfo = await userManager.GetUsersAsync(userId);

        return await GetSummaryAsync(userInfo);
    }

    public async Task<UserSummaryWebhookDto> GetSummaryAsync(UserInfo userInfo)
    {
        if (userInfo == null || userInfo.Equals(Constants.LostUser))
        {
            return null;
        }

        var cacheKey = Math.Abs(userInfo.LastModified.GetHashCode());

        var result = new UserSummaryWebhookDto
        {
            Id = userInfo.Id,
            DisplayName = displayUserSettingsHelper.GetFullUserName(userInfo),
            UserName = userInfo.UserName,
            Email = userInfo.Email,
            Avatar = await userPhotoManager.GetBigPhotoURL(userInfo.Id) + $"?hash={cacheKey}"
        };

        if (userInfo.Id != Guid.Empty)
        {
            result.ProfileUrl = commonLinkUtility.GetFullAbsolutePath(await commonLinkUtility.GetUserProfileAsync(userInfo.Id));
        }

        return result;
    }

    private static void FillContacts(UserWebhookDto result, UserInfo userInfo)
    {
        if (userInfo.ContactsList == null)
        {
            return;
        }

        var contacts = new List<ContactWebhookDto>();

        for (var i = 0; i + 1 < userInfo.ContactsList.Count; i += 2)
        {
            contacts.Add(new ContactWebhookDto { Type = userInfo.ContactsList[i], Value = userInfo.ContactsList[i + 1] });
        }

        if (contacts.Count > 0)
        {
            result.Contacts = contacts;
        }
    }

    private async Task FillGroupsAsync(UserWebhookDto result, UserInfo userInfo)
    {
        var groupsFromDb = await userManager.GetUserGroupsAsync(userInfo.Id);

        List<GroupSummaryWebhookDto> groups = [];

        foreach (var g in groupsFromDb)
        {
            groups.Add(new GroupSummaryWebhookDto
            {
                Id = g.ID,
                Name = g.Name,
                Manager = (await userManager.GetUsersAsync(await userManager.GetDepartmentManagerAsync(g.ID))).UserName,
                IsSystem = await userManager.IsSystemGroup(g.ID) ? true : null
            });
        }

        if (groups.Count > 0)
        {
            result.Groups = groups;
            result.Department = string.Join(", ", groups.Select(d => d.Name.HtmlEncode()));
        }
        else
        {
            result.Department = "";
        }
    }

    private async Task FillAvatarsAsync(UserWebhookDto result, UserInfo userInfo)
    {
        var cacheKey = Math.Abs(userInfo.LastModified.GetHashCode());

        result.HasAvatar = await userPhotoManager.UserHasAvatar(userInfo.Id);
        result.Avatar = await userPhotoManager.GetBigPhotoURL(userInfo.Id) + $"?hash={cacheKey}";
        result.AvatarOriginal = await userPhotoManager.GetPhotoAbsoluteWebPath(userInfo.Id) + $"?hash={cacheKey}";
        result.AvatarMax = await userPhotoManager.GetMaxPhotoURL(userInfo.Id) + $"?hash={cacheKey}";
        result.AvatarMedium = await userPhotoManager.GetMediumPhotoURL(userInfo.Id) + $"?hash={cacheKey}";
        result.AvatarSmall = await userPhotoManager.GetSmallPhotoURL(userInfo.Id) + $"?hash={cacheKey}";

        if (userInfo.Id != Guid.Empty)
        {
            result.ProfileUrl = commonLinkUtility.GetFullAbsolutePath(await commonLinkUtility.GetUserProfileAsync(userInfo.Id));
        }
    }

    private async Task FillQuotaAsync(UserWebhookDto result, UserInfo userInfo, Tenant tenant)
    {
        if (!coreBaseSettings.Standalone && !(await tenantManager.GetCurrentTenantQuotaAsync()).Statistic)
        {
            return;
        }

        var quotaSettings = await settingsManager.LoadAsync<TenantUserQuotaSettings>();

        result.UsedSpace = Math.Max(0, (await quotaService.FindUserQuotaRowsAsync(tenant.Id, userInfo.Id))
            .Where(r => !string.IsNullOrEmpty(r.Tag) && !string.Equals(r.Tag, Guid.Empty.ToString()))
            .Sum(r => r.Counter));

        if (!quotaSettings.EnableQuota)
        {
            return;
        }

        var userQuotaSettings = await settingsManager.LoadAsync<UserQuotaSettings>(userInfo);

        result.IsCustomQuota = userQuotaSettings != null && userQuotaSettings.UserQuota != userQuotaSettings.GetDefault().UserQuota;

        result.QuotaLimit = userQuotaSettings != null
            ? userQuotaSettings.UserQuota != userQuotaSettings.GetDefault().UserQuota ? userQuotaSettings.UserQuota : quotaSettings.DefaultQuota
            : quotaSettings.DefaultQuota;
    }
}
