//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Data.Backup.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BackupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackupResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Data.Backup.Core.BackupResource", typeof(BackupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic backup.
        /// </summary>
        internal static string AutoBackup {
            get {
                return ResourceManager.GetString("AutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while creating the backup. Please try creating it again or contact support..
        /// </summary>
        internal static string BackupException {
            get {
                return ResourceManager.GetString("BackupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup file is invalid..
        /// </summary>
        internal static string BackupInvalid {
            get {
                return ResourceManager.GetString("BackupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files were not included in the backup. For more details, please check {0}.
        /// </summary>
        internal static string BackupMissingFilesWarning {
            get {
                return ResourceManager.GetString("BackupMissingFilesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup file is invalid. Please use the file created in the same portal..
        /// </summary>
        internal static string BackupNotFound {
            get {
                return ResourceManager.GetString("BackupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom cloud.
        /// </summary>
        internal static string BackupStorageTypeCustomCloud {
            get {
                return ResourceManager.GetString("BackupStorageTypeCustomCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary storage.
        /// </summary>
        internal static string BackupStorageTypeDataStore {
            get {
                return ResourceManager.GetString("BackupStorageTypeDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup room.
        /// </summary>
        internal static string BackupStorageTypeDocuments {
            get {
                return ResourceManager.GetString("BackupStorageTypeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file.
        /// </summary>
        internal static string BackupStorageTypeLocal {
            get {
                return ResourceManager.GetString("BackupStorageTypeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party storage.
        /// </summary>
        internal static string BackupStorageTypeThirdPartyConsumer {
            get {
                return ResourceManager.GetString("BackupStorageTypeThirdPartyConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party resource.
        /// </summary>
        internal static string BackupStorageTypeThridpartyDocuments {
            get {
                return ResourceManager.GetString("BackupStorageTypeThridpartyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string ButtonSetPassword {
            get {
                return ResourceManager.GetString("ButtonSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is larger than the total size of the portal.
        /// </summary>
        internal static string LargeBackup {
            get {
                return ResourceManager.GetString("LargeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while restoring the backup. Please try restoring it again or contact support..
        /// </summary>
        internal static string RestoreException {
            get {
                return ResourceManager.GetString("RestoreException", resourceCulture);
            }
        }
    }
}
