<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" />
        <PackageReference Include="Aspire.Hosting.Testing" />
        <PackageReference Include="DocSpace.API.SDK" />
        <PackageReference Include="xunit.v3.extensibility.core" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ASC.AppHost\ASC.AppHost.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
