server:
  socket:
    host: ${SOCKET_SERVER_HOST:127.0.0.1}
    port: ${SOCKET_SERVER_PORT:8585}
  host: ${SERVER_HOST:127.0.0.1}
  port: ${SERVER_PORT:9090}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: false

application:
  security:
    cipherSecret: ${CIPHER_SECRET:secret}
  scopes:
    -
      name: accounts:read
      group: accounts
      type: read
    -
      name: accounts:write
      group: accounts
      type: write
    -
      name: rooms:read
      group: rooms
      type: read
    -
      name: rooms:write
      group: rooms
      type: write
    -
      name: accounts.self:read
      group: profiles
      type: read
    -
      name: accounts.self:write
      group: profiles
      type: write
    -
      name: files:read
      group: files
      type: read
    -
      name: files:write
      group: files
      type: write

messaging:
  rabbitmq:
    configuration:
      authorization:
        exchange: authorization.exchange
        queue: authorization.queue
        routing: authorization.routing
        deadExchange: authorization.dead.exchange
        deadQueue: authorization.dead.queue
        deadRouting: authorization.dead.routing
      client:
        exchange: client.exchange
        queue: client.queue
        routing: client.routing
        deadExchange: client.dead.exchange
        deadQueue: client.dead.queue
        deadRouting: client.dead.routing
      consent:
        exchange: consent.exchange
        queue: consent.queue
        routing: consent.routing
        deadExchange: consent.dead.exchange
        deadQueue: consent.dead.queue
        deadRouting: consent.dead.routing
      socket:
        exchange: socket.exchange
        queue: ${random.uuid}
        routing: socket.routing
        deadExchange: socket.dead.exchange
        deadQueue: socket.dead.queue
        deadRouting: socket.dead.routing

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids: true
      client:
        config:
          default:
            connectTimeout: 1500
            readTimeout: 3000
  flyway:
    enabled: true
    baselineOnMigrate: true
    url: jdbc:mysql://${JDBC_URL:127.0.0.1:33060}/${JDBC_DATABASE:docspace}
    user: ${JDBC_USER_NAME:root}
    password: ${JDBC_PASSWORD:my-secret-pw}
    schemas: ${JDBC_DATABASE:docspace}
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    locations: classpath:migration
  application:
    name: ASC.Identity.Authorization.API
  profiles:
    active: ${PROFILE:dev}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          time_zone: UTC
          batch_size: 100
        order_inserts: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${JDBC_URL:127.0.0.1:33060}/${JDBC_DATABASE:docspace}
    username: ${JDBC_USER_NAME:root}
    password: ${JDBC_PASSWORD:my-secret-pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER_NAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 3000
          multiplier: 3.0

resilience4j:
  circuitbreaker:
    instances:
      docspace:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      getClientRetryRateLimiter:
        maxRetryAttempts: 2
        waitDuration: 1s
      batchClientRetryRateLimiter:
        maxRetryAttempts: 2
        waitDuration: 1s
      regenerateClientSecretRetryRateLimiter:
        maxRetryAttempts: 2
        waitDuration: 1s
      updateClientRetryRateLimiter:
        maxRetryAttempts: 4
        waitDuration: 1s
      getScopesRetryRateLimiter:
        maxRetryAttempts: 2
        waitDuration: 1s
  ratelimiter:
    configs:
      default:
        limitRefreshPeriod: 1s
        limitForPeriod: 1000
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      batchClientRateLimiter:
        baseConfig: default
        limitForPeriod: 500
      getClientRateLimiter:
        baseConfig: default
      regenerateClientSecretRateLimiter:
        baseConfig: default
        limitForPeriod: 15
      updateClientRateLimiter:
        baseConfig: default
        limitForPeriod: 15
      getScopesRateLimiter:
        baseConfig: default
  timelimiter:
    instances:
      mutateTimeLimiter:
        timeoutDuration: 2s
      readTimeLimiter:
        timeoutDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    org:
      hibernate:
        stat: DEBUG
        SQL: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  config: classpath:log4j2-dev.xml