resilience4j:
  retry:
    instances:
      grpcClientRetry:
        maxAttempts: ${RETRY_GRPC_CLIENT_MAX_ATTEMPTS:3}
        waitDuration: ${RETRY_GRPC_CLIENT_WAIT_DURATION:200ms}
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: ${RETRY_GRPC_CLIENT_MULTIPLIER:1.625}
        retryExceptions:
          - io.grpc.StatusRuntimeException
        ignoreExceptions:
          - com.asc.authorization.application.exception.client.RegisteredClientPermissionException
          - com.asc.authorization.application.exception.client.NonRetryableGrpcException
