grpc:
  client:
    registrationService:
      address: ${GRPC_CLIENT_REGISTRATION_ADDRESS:static://localhost:8888}
      negotiation-type: ${GRPC_CLIENT_REGISTRATION_NEGOTIATION_TYPE:plaintext}
  server:
    port: ${GRPC_AUTHORIZATION_SERVER_PORT:9999}
    security:
      enabled: ${GRPC_AUTHORIZATION_SERVER_SECURITY_ENABLED:false}
      certificateChainPath: ${GRPC_AUTHORIZATION_SERVER_SECURITY_CERTIFICATE_PATH:classpath:certs/server.crt}
      privateKeyPath: ${GRPC_AUTHORIZATION_SERVER_SECURITY_PRIVATE_KEY_PATH:classpath:certs/server.key}
      clientAuth: NONE