#!/usr/bin/env python3
"""
Emit the trigger -> payload dispatch table for one language, from the
x-docspace-trigger-payloads block of the webhook contract.

This table is never hand-maintained: 37 triggers across 9 languages is exactly
the kind of list that silently rots. Adding a trigger to WebhookTrigger.cs and
the contract is enough -- rerunning generate.sh carries it everywhere.

    python gen-trigger-map.py --lang typescript --spec <yaml> --out <file>
"""

import argparse
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

HEADER = (
    "Trigger -> payload dispatch, generated from docspace-webhooks.yaml by\n"
    "tools/gen-trigger-map.py. Do not edit; rerun ./generate.sh instead."
)


def typescript(trigger_map, schemas, args):
    payloads = sorted({p for p in trigger_map.values() if p})

    imports = ",\n".join(
        f"    {p},\n    {p}FromJSON" for p in payloads
    )

    type_rows = "\n".join(
        f"    {_ts_key(t)}: {p if p else 'unknown'};"
        for t, p in trigger_map.items()
    )

    deser_rows = "\n".join(
        f"    {_ts_key(t)}: {p + 'FromJSON' if p else 'identity'},"
        for t, p in trigger_map.items()
    )

    return f"""/* eslint-disable */
/**
 * {HEADER.replace(chr(10), chr(10) + " * ")}
 */
import {{
{imports},
}} from './models';

const identity = (json: any): unknown => json;

/** Every trigger DocSpace can send, mapped to the payload it carries. */
export interface TriggerPayloadMap {{
{type_rows}
}}

/** Trigger names as they appear in `event.trigger`. */
export type WebhookTriggerName = keyof TriggerPayloadMap;

/**
 * Runtime deserializers, keyed the same way. `'*'` is the legacy catch-all the
 * server emits only when it cannot read a stored payload; it stays opaque.
 */
export const PAYLOAD_DESERIALIZERS: {{
    [K in WebhookTriggerName]: (json: any) => TriggerPayloadMap[K];
}} = {{
{deser_rows}
}};

/** True when `trigger` is one this build of the SDK knows about. */
export function isKnownTrigger(trigger: string): trigger is WebhookTriggerName {{
    return Object.prototype.hasOwnProperty.call(PAYLOAD_DESERIALIZERS, trigger);
}}
"""


def _ts_key(trigger):
    return "'" + trigger.replace("\\", "\\\\").replace("'", "\\'") + "'"


def csharp(trigger_map, schemas, args):
    rows = chr(10).join(
        f'            ["{t}"] = typeof({p}),'
        for t, p in trigger_map.items() if p
    )
    catchall = ", ".join(f'"{t}"' for t, p in trigger_map.items() if not p)

    return f"""// <auto-generated>
//
// {HEADER.replace(chr(10), chr(10) + "// ")}
//
using System;
using System.Collections.Generic;

using {args.model_package};

namespace {args.package};

/// <summary>Which payload type each DocSpace trigger carries.</summary>
public static class WebhookTriggers
{{
    /// <summary>Trigger name to payload type, for every trigger with a typed body.</summary>
    public static readonly IReadOnlyDictionary<string, Type> PayloadTypes =
        new Dictionary<string, Type>(StringComparer.Ordinal)
        {{
{rows}
        }};

    /// <summary>
    /// The legacy catch-all ({catchall}). The server sends it only when it cannot
    /// read a stored payload, and it carries no typed body.
    /// </summary>
    public static readonly IReadOnlySet<string> UntypedTriggers =
        new HashSet<string>(StringComparer.Ordinal) {{ {catchall} }};

    /// <summary>True when this build knows how to type the trigger's payload.</summary>
    public static bool IsKnown(string trigger) =>
        trigger is not null && PayloadTypes.ContainsKey(trigger);
}}
"""


def java(trigger_map, schemas, args):
    """
    The generator's JSON supporting class, which models-only output omits even
    though every model calls JSON.getGson(). It has to register one
    CustomTypeAdapterFactory per model -- a list that must track the contract,
    which is why it is emitted here rather than hand-written in java/shim/.
    """
    factories = chr(10).join(
        f"            .registerTypeAdapterFactory("
        f"new {name}.CustomTypeAdapterFactory())"
        for name in sorted(schemas)
    )

    return f"""package {args.package};

// {HEADER.replace(chr(10), chr(10) + "// ")}

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializer;

import {args.model_package}.*;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;

public final class JSON {{

    private static final Gson GSON = new GsonBuilder()
            // Gson has no built-in OffsetDateTime support.
            .registerTypeAdapter(OffsetDateTime.class,
                    (JsonDeserializer<OffsetDateTime>) (json, type, ctx) ->
                            OffsetDateTime.parse(json.getAsString(),
                                    DateTimeFormatter.ISO_OFFSET_DATE_TIME))
            .registerTypeAdapter(OffsetDateTime.class,
                    (JsonSerializer<OffsetDateTime>) (src, type, ctx) ->
                            new JsonPrimitive(
                                    DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(src)))
{factories}
            .create();

    private JSON() {{
    }}

    public static Gson getGson() {{
        return GSON;
    }}
}}
"""


def markdown(trigger_map, schemas, args):
    """
    A reference table of every trigger and the payload it carries.

    openapi-generator cannot produce this: x-docspace-trigger-payloads is a
    root-level vendor extension, and mustache templates only ever see the model
    and operation trees. So the contract's own map is rendered here instead.
    """
    doc_path = args.doc_path or ""

    # This page is published on the public documentation site, so it describes
    # only what a subscriber needs. How it is produced, and how the server
    # happens to serialize its payloads, are not part of that -- the only trace
    # left is an HTML comment, which renders as nothing.
    titles = {
        "user": "Users",
        "group": "Groups",
        "file": "Files",
        "folder": "Folders",
        "room": "Rooms",
        "agent": "Agents",
        "form": "Forms",
    }

    families, order = {}, []
    for trigger, payload in trigger_map.items():
        if trigger == "*":
            continue  # described in prose below, not a row in any table
        family = trigger.split(".")[0]
        if family not in families:
            families[family] = []
            order.append(family)
        families[family].append((trigger, payload))

    sections = []
    for family in order:
        rows = chr(10).join(
            f"| `{trigger}` | [`{payload}`]({doc_path}{payload}.md) |"
            for trigger, payload in families[family]
        )
        sections.append(
            f"## {titles.get(family, family.title())}\n\n"
            f"| Event | Payload |\n|---|---|\n{rows}\n"
        )

    body = chr(10).join(sections)
    total = len([t for t in trigger_map if t != "*"])

    return f"""<!-- Generated from the DocSpace webhook contract. Do not edit by hand. -->

# Webhook events

DocSpace can notify your endpoint about {total} events. Each delivery names the
one that caused it in `event.trigger`, and carries that event's subject in
`payload`.

A subscription chooses which events it wants. Subscribe to `*` to receive all of
them, including any added in future. `GET api/2.0/settings/webhook/triggers`
lists every event with the value to subscribe with, and whether your role is
allowed to.

## Payloads

Files, folders, rooms, agents and forms all deliver the **same payload shape**.
Nothing in it is specific to one kind of entry, so use `fileEntryType` to tell
them apart: `1` is a folder, `2` is a file.

Note that a file's name arrives in `title`, and that absent fields are simply
defaults — a property missing from the JSON means empty, `false` or zero, never
"unknown".

{body}
## Events added later

New events are introduced over time, and a subscription to `*` will start
receiving them as soon as the portal is upgraded. Treat an unfamiliar
`event.trigger` as something to ignore rather than an error, so an upgrade
cannot break your endpoint.
"""


EMITTERS = {
    "typescript": typescript,
    "csharp": csharp,
    "java": java,
    "markdown": markdown,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang", required=True, choices=sorted(EMITTERS))
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", required=True)
    # Package names are passed in rather than hardcoded: they have to track the
    # additional-properties in generate.sh, and those follow the API SDK naming.
    ap.add_argument("--package", default="")
    ap.add_argument("--model-package", dest="model_package", default="")
    # Relative path from the emitted file to the per-model docs.
    ap.add_argument("--doc-path", dest="doc_path", default="")
    args = ap.parse_args()

    with open(args.spec, encoding="utf-8") as fh:
        spec = yaml.safe_load(fh)

    block = spec.get("x-docspace-trigger-payloads")
    if not block or not block.get("map"):
        sys.exit("x-docspace-trigger-payloads.map missing from the contract")

    trigger_map = block["map"]
    schemas = spec.get("components", {}).get("schemas", {})

    unknown = sorted({p for p in trigger_map.values() if p and p not in schemas})
    if unknown:
        sys.exit(f"trigger map references undefined schemas: {', '.join(unknown)}")

    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(EMITTERS[args.lang](trigger_map, schemas, args))

    print(f"{args.out}: {len(trigger_map)} triggers", file=sys.stderr)


if __name__ == "__main__":
    main()
