//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.AI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.AI.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to manage AI settings.
        /// </summary>
        internal static string AiSettingsAccessDenied {
            get {
                return ResourceManager.GetString("AiSettingsAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process files: {0}. Files may be corrupted or encrypted.
        /// </summary>
        internal static string AttachmentProcessFailed {
            get {
                return ResourceManager.GetString("AttachmentProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to use chat.
        /// </summary>
        internal static string ChatAccessDenied {
            get {
                return ResourceManager.GetString("ChatAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat not found.
        /// </summary>
        internal static string ChatNotFound {
            get {
                return ResourceManager.GetString("ChatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect provider type.
        /// </summary>
        internal static string IncorrectProvider {
            get {
                return ResourceManager.GetString("IncorrectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. Verify your credentials.
        /// </summary>
        internal static string IncorrectServerCredentials {
            get {
                return ResourceManager.GetString("IncorrectServerCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authorization code.
        /// </summary>
        internal static string InvalidAuthCode {
            get {
                return ResourceManager.GetString("InvalidAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified API key is invalid or does not have access rights. Verify that the key is correct and try again.
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MCP server name. Only letters, numbers, underscores, and hyphens are allowed.
        /// </summary>
        internal static string InvalidServerName {
            get {
                return ResourceManager.GetString("InvalidServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL path specified is invalid. Please ensure the correct endpoint is used.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to manage providers.
        /// </summary>
        internal static string ManageProviders {
            get {
                return ResourceManager.GetString("ManageProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to manage MCP servers.
        /// </summary>
        internal static string ManageServers {
            get {
                return ResourceManager.GetString("ManageServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider not found.
        /// </summary>
        internal static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP server name is not allowed.
        /// </summary>
        internal static string ReservedServerName {
            get {
                return ResourceManager.GetString("ReservedServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to MCP server.
        /// </summary>
        internal static string ServerFailedConnect {
            get {
                return ResourceManager.GetString("ServerFailedConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP server name is already exists.
        /// </summary>
        internal static string ServerNameExists {
            get {
                return ResourceManager.GetString("ServerNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP server not found.
        /// </summary>
        internal static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of servers per room is {0}.
        /// </summary>
        internal static string ServersRoomLimit {
            get {
                return ResourceManager.GetString("ServersRoomLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP servers are unavailable: {0}. Check connection settings.
        /// </summary>
        internal static string UnavailableServers {
            get {
                return ResourceManager.GetString("UnavailableServers", resourceCulture);
            }
        }
    }
}
