//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Migration.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MigrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Migration.Core.Resources.MigrationResource", typeof(MigrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add user {0} to group {1}.
        /// </summary>
        public static string CanNotAddUserInGroup {
            get {
                return ResourceManager.GetString("CanNotAddUserInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create file {0}.
        /// </summary>
        public static string CanNotCreateFile {
            get {
                return ResourceManager.GetString("CanNotCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t import user.
        /// </summary>
        public static string CanNotImportUser {
            get {
                return ResourceManager.GetString("CanNotImportUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t import user files.
        /// </summary>
        public static string CanNotImportUserFiles {
            get {
                return ResourceManager.GetString("CanNotImportUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse {0} archive.
        /// </summary>
        public static string CanNotParseArchive {
            get {
                return ResourceManager.GetString("CanNotParseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse archives.
        /// </summary>
        public static string CanNotParseArchives {
            get {
                return ResourceManager.GetString("CanNotParseArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse user {0}.
        /// </summary>
        public static string CanNotParseUser {
            get {
                return ResourceManager.GetString("CanNotParseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read info file from {0}.
        /// </summary>
        public static string CanNotReadInfoFile {
            get {
                return ResourceManager.GetString("CanNotReadInfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t share entry {0} to {1}.
        /// </summary>
        public static string CanNotShare {
            get {
                return ResourceManager.GetString("CanNotShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t unzip {0}.
        /// </summary>
        public static string CanNotToUnzip {
            get {
                return ResourceManager.GetString("CanNotToUnzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file {0}.
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder {0}.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create shared room {0}.
        /// </summary>
        public static string CreateShareRoom {
            get {
                return ResourceManager.GetString("CreateShareRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing....
        /// </summary>
        public static string DataProcessing {
            get {
                return ResourceManager.GetString("DataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing completed.
        /// </summary>
        public static string DataProcessingCompleted {
            get {
                return ResourceManager.GetString("DataProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database parsing.
        /// </summary>
        public static string DumpParse {
            get {
                return ResourceManager.GetString("DumpParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group migration {0} ({1}/{2}).
        /// </summary>
        public static string GroupMigration {
            get {
                return ResourceManager.GetString("GroupMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating user files {0} ({1}/{2}).
        /// </summary>
        public static string MigratingUserFiles {
            get {
                return ResourceManager.GetString("MigratingUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration common files.
        /// </summary>
        public static string MigrationCommonFiles {
            get {
                return ResourceManager.GetString("MigrationCommonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed.
        /// </summary>
        public static string MigrationCompleted {
            get {
                return ResourceManager.GetString("MigrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such migration provider.
        /// </summary>
        public static string MigrationNotFoundException {
            get {
                return ResourceManager.GetString("MigrationNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration is in progress.
        /// </summary>
        public static string MigrationProgressException {
            get {
                return ResourceManager.GetString("MigrationProgressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration project files.
        /// </summary>
        public static string MigrationProjectFiles {
            get {
                return ResourceManager.GetString("MigrationProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for migration.
        /// </summary>
        public static string PreparingForMigration {
            get {
                return ResourceManager.GetString("PreparingForMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting data processing....
        /// </summary>
        public static string StartOfDataProcessing {
            get {
                return ResourceManager.GetString("StartOfDataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping....
        /// </summary>
        public static string Unzipping {
            get {
                return ResourceManager.GetString("Unzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping completed....
        /// </summary>
        public static string UnzippingFinished {
            get {
                return ResourceManager.GetString("UnzippingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User migration {0} ({1}/{2}).
        /// </summary>
        public static string UserMigration {
            get {
                return ResourceManager.GetString("UserMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t import common files.
        /// </summary>
        public static string СanNotImportCommonFiles {
            get {
                return ResourceManager.GetString("СanNotImportCommonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t import project files.
        /// </summary>
        public static string СanNotImportProjectFiles {
            get {
                return ResourceManager.GetString("СanNotImportProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create root folder.
        /// </summary>
        public static string СreateRootFolder {
            get {
                return ResourceManager.GetString("СreateRootFolder", resourceCulture);
            }
        }
    }
}
