client:
  cache:
    redis:
      enabled: ${CLIENT_CACHE_REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl: ${REDIS_SSL:false}
      timeout: ${REDIS_TIMEOUT:2s}
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE:32}
        max-idle: ${REDIS_POOL_MAX_IDLE:16}
        min-idle: ${REDIS_POOL_MIN_IDLE:0}
        max-wait: ${REDIS_POOL_MAX_WAIT:200ms}
