hazelcast:
  cluster-name: identity-registration
  network:
    port:
      auto-increment: true
      port-count: 100
      port: 5701
    outbound-ports:
      - 0
    join:
      multicast:
        enabled: true
        multicast-group: 224.2.2.3
        multicast-port: 54327
        multicast-time-to-live: 32
        multicast-timeout-seconds: 2
      kubernetes:
        enabled: false
        namespace: default
        service-name: identity-registration-hazelcast
  map:
    scopes:
      in-memory-format: BINARY
      backup-count: 1
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 5
    clients:
      in-memory-format: BINARY
      backup-count: 2
      async-backup-count: 1
      time-to-live-seconds: 180
      max-idle-seconds: 180
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 20
      merge-policy:
        batch-size: 100
        class-name: com.hazelcast.spi.merge.PutIfAbsentMergePolicy
      cache-deserialized-values: INDEX_ONLY
      statistics-enabled: true
    clientsInfo:
      in-memory-format: BINARY
      backup-count: 2
      async-backup-count: 1
      time-to-live-seconds: 180
      max-idle-seconds: 180
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 20
      merge-policy:
        batch-size: 100
        class-name: com.hazelcast.spi.merge.PutIfAbsentMergePolicy
      cache-deserialized-values: INDEX_ONLY
      statistics-enabled: true
    ascMe:
      in-memory-format: BINARY
      backup-count: 1
      time-to-live-seconds: 15
      max-idle-seconds: 0
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 5
    ascEmail:
      in-memory-format: BINARY
      backup-count: 1
      time-to-live-seconds: 15
      max-idle-seconds: 0
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 5
    ascTenant:
      in-memory-format: BINARY
      backup-count: 1
      time-to-live-seconds: 15
      max-idle-seconds: 0
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 5
    ascSettings:
      in-memory-format: BINARY
      backup-count: 1
      time-to-live-seconds: 15
      max-idle-seconds: 0
      eviction:
        eviction-policy: LRU
        max-size-policy: USED_HEAP_SIZE
        size: 5
  metrics:
    enabled: true
    management-center:
      enabled: true
      retention-seconds: 5
    jmx:
      enabled: true
    collection-frequency-seconds: 5