version: "3.8"

services:
  onlyoffice-oauth-authorization:
    build:
      context: ./
      dockerfile: ${OAUTH_AUTHORIZATION_DOCKERFILE}
    container_name: onlyoffice-oauth-authorization
    restart: always
    ports:
      - 8080:8080
    environment:
      PROFILE: ${PROFILE}
      JDBC_URL: ${JDBC_URL}
      JDBC_DATABASE: ${JDBC_DATABASE}
      JDBC_USER_NAME: ${JDBC_USER_NAME}
      JDBC_PASSWORD: ${JDBC_PASSWORD}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER_NAME: ${RABBIT_USER_NAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      DOCSPACE_ADDRESS: ${DOCSPACE_ADDRESS}
  onlyoffice-oauth-api:
    build:
      context: ./
      dockerfile: ${OAUTH_API_DOCKERFILE}
    container_name: onlyoffice-oauth-api
    ports:
      - 9090:9090
      - 8585:8585
    environment:
      PROFILE: ${PROFILE}
      JDBC_URL: ${JDBC_URL}
      JDBC_DATABASE: ${JDBC_DATABASE}
      JDBC_USER_NAME: ${JDBC_USER_NAME}
      JDBC_PASSWORD: ${JDBC_PASSWORD}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER_NAME: ${RABBIT_USER_NAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      DOCSPACE_ADDRESS: ${DOCSPACE_ADDRESS}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
