//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ASC.People.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class PeopleResource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeopleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ASC.People.Resources.PeopleResource", typeof(PeopleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file could not be found.
        /// </summary>
        internal static string ErrorEmptyUploadFileSelected {
            get {
                return ResourceManager.GetString("ErrorEmptyUploadFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size is too large.
        /// </summary>
        internal static string ErrorImageSizetLimit {
            get {
                return ResourceManager.GetString("ErrorImageSizetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file size is too large.
        /// </summary>
        internal static string ErrorImageWeightLimit {
            get {
                return ResourceManager.GetString("ErrorImageWeightLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown image file type.
        /// </summary>
        internal static string ErrorUnknownFileImageType {
            get {
                return ResourceManager.GetString("ErrorUnknownFileImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do the same as a user|Create profiles and groups|Import profiles|Invite users.
        /// </summary>
        internal static string ProductAdminOpportunities {
            get {
                return ResourceManager.GetString("ProductAdminOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new users, invite or import them. Manage users and view their detailed information..
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profiles and groups.
        /// </summary>
        internal static string ProductUserOpportunities {
            get {
                return ResourceManager.GetString("ProductUserOpportunities", resourceCulture);
            }
        }
    }
}
